In [1]:
import numpy as np

In [2]:
A = np.random.randn(10)
A

array([ 0.49442175,  0.84079802, -0.95734868, -1.44017131,  0.83417694,
        0.02275527, -0.53719239, -0.62869171,  0.49453118,  1.35247727])

In [3]:
B = np.random.randn(10)

In [7]:
np.add(A,B)

array([ 0.16219869, -0.70809784, -1.8784952 , -1.22200766,  0.13490266,
        0.63344471, -1.31105066, -0.39392778,  0.83718247, -0.13140737])

In [6]:
np.maximum(A,B)

array([ 0.49442175,  0.84079802, -0.92114651,  0.21816365,  0.83417694,
        0.61068944, -0.53719239,  0.23476393,  0.49453118,  1.35247727])

In [11]:
arr = np.arange(10)

In [12]:
np.save('myarray',arr)

In [14]:
np.load('myarray.npy')
arr2 = arr

In [15]:
np.savez('ziparray.npz',x=arr, y =arr2)

In [18]:
archive_array = np.load('ziparray.npz')
archive_array['y']


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.savetxt('mytext.txt',arr,delimiter=',')
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])